### ISSUE TITLE
Error: ENOENT, no such file or directory 'index.html'

### ISSUE THREAD

**Issue by basavaraj1985** [pavanratnakar/Single-Page-App-React-Flux#1]
Just wanted to check out. Followed your steps in documentation, results in error :(

Error:
Error: ENOENT, no such file or directory 'index.html'
   at Object.fs.openSync (fs.js:439:18)
   at Object.fs.readFileSync (fs.js:290:15)
   at /Users/bm3/Code/public/Single-Page-App-React-Flux/lib/router.js:46:20
   at Layer.handle [as handle_request](/Users/bm3/Code/public/Single-Page-App-React-Flux/node_modules/express/lib/router/layer.js:82:5)
   at next (/Users/bm3/Code/public/Single-Page-App-React-Flux/node_modules/express/lib/router/route.js:110:13)
   at Route.dispatch (/Users/bm3/Code/public/Single-Page-App-React-Flux/node_modules/express/lib/router/route.js:91:3)
   at Layer.handle [as handle_request](/Users/bm3/Code/public/Single-Page-App-React-Flux/node_modules/express/lib/router/layer.js:82:5)
   at /Users/bm3/Code/public/Single-Page-App-React-Flux/node_modules/express/lib/router/index.js:267:22
   at Function.proto.process_params (/Users/bm3/Code/public/Single-Page-App-React-Flux/node_modules/express/lib/router/index.js:321:12)
   at next (/Users/bm3/Code/public/Single-Page-App-React-Flux/node_modules/express/lib/router/index.js:261:10)

**Comment by pavanratnakar** [comment]
updated doc....can u try now
